on:
  workflow_dispatch:
  push:
    paths:
      - '.github/workflows/diva_orcid_kthid.yml'
  schedule:
    - cron: '0 7 * * *' # [minute hour day_of_month month day_of_week], see https://crontab.guru/#0_7_*_*_*

name: Upload DiVA ORCiD / kthId pairs to object storage

jobs:
  docker:
    runs-on: ubuntu-latest
    container: ghcr.io/kth-library/kthcorpus
    timeout-minutes: 20
    env:
      MC_HOST_kthb: ${{ secrets.MC_HOST_KTHB }}
    steps:
      - run: |
          R -e 'library(kthcorpus); diva_orcid_kthid_upload();'
