# Workflow derived from https://github.com/r-lib/actions/tree/v2/examples
# Need help debugging build failures? Start at https://github.com/r-lib/actions#where-to-find-help
on:
  workflow_dispatch:
  push:
    paths:
      - '.github/workflows/report-other.yml'
  schedule:
    - cron: '0 7 * * *' # https://crontab.guru/#0_7_*_*_*

name: Generate report using latest kthcorpus container

jobs:
  docker:
    runs-on: ubuntu-latest
    container: ghcr.io/kth-library/kthcorpus
    timeout-minutes: 20
    env:
      MC_HOST_kthb: ${{ secrets.MC_HOST_KTHB }}
      TZ: Europe/Stockholm
    steps:
      - run: |
          R -e 'checks_render_report(file.path(dirname(checks_report_path()), "checks-report-other.Rmd")); kthcorpus:::diva_upload_s3("/tmp/checks-report-other.html")'

      - name: Upload results as GitHub Artifact
        uses: actions/upload-artifact@main
        with:
          name: report
          path: /tmp/checks-report-other.html
