# Workflow derived from https://github.com/r-lib/actions/tree/v2/examples
# Need help debugging build failures? Start at https://github.com/r-lib/actions#where-to-find-help
on:
  workflow_dispatch:
  push:
    paths:
      - '.github/workflows/report.yml'
  schedule:
    - cron: '*/30 * * * *' # UTC 49th min after 01th hour every day of month, month, day of week

name: Generate report using latest kthcorpus container

jobs:
  docker:
    runs-on: ubuntu-latest
    container: ghcr.io/kth-library/kthcorpus
    timeout-minutes: 15
    env:
      MC_HOST_kthb: ${{ secrets.MC_HOST_KTHB }}
    steps:
      - run: |
          R -e 'library(kthcorpus); diva_refresh_trigger();'

      - name: Upload results as GitHub Artifact
        uses: actions/upload-artifact@main
        with:
          name: report
          path: /tmp/checks-report.html
