on:
  workflow_dispatch:
  push:
    paths:
      - '.github/workflows/scopus.yml'
  schedule:
    - cron: '0 9 * * *' # UTC 49th min after 01th hour every day of month, month, day of week

name: Request publications from Scopus API and upload to S3/minio

jobs:
  docker:
    runs-on: ubuntu-latest
    container: ghcr.io/kth-library/kthcorpus
    timeout-minutes: 20
    env:
      MC_HOST_kthb: ${{ secrets.MC_HOST_KTHB }}
      SCOPUS_API_KEY: ${{ secrets.SCOPUS_API_KEY }}
      SCOPUS_API_INSTTOKEN: ${{ secrets.SCOPUS_API_INSTTOKEN }}
    steps:
      - run: |
          R -e 'library(kthcorpus); scopus_upload();'
